# Generated by Django 5.0.3 on 2024-04-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=290)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=290)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
